---

server:
  url: "http://localhost:8080/stat"
  app: "stream"
  type: "nginx-rtmp"
  #xpath: "/rtmp/server/application[name/text()='%s']/live/stream[active]/name/text()"

  # Alternatively:
  #url: "http://localhost:8000/status-json.xsl"
  #type: "icecast"

  # Alternatively:
  #type: "static"
  #streams:
  #  - "s1_native_hd"
  #  - "s2_native_hd"

#metrics:
#  influx:
#    host: "http://127.0.0.1:8086"
#    database: "..."
#    username: "..."
#    password: "..."

#times:
#  source_restart_delay: 3
#  source_timeout: 2
#  sink_restart_delay: 3
#  server_poll_interval: 5
#  server_request_timeout: 3
#  server_timeout: 16
#  idle_time: 0

#misc:
#  reuse_screens: true
#  restart_when_sink_dies: false

source_buffer:
  buffer_count: 64
  buffer_size: 131072

sink_buffer:
  buffer_count: 24

flows:
  "video":
    regexp: "^s\\d+_(native|translated)_(hd|sd)$"
    source: "source_1.sh {stream}"
    sinks:
      "sink_1": "sink_1.sh {stream}"
      "sink_2": "sink_2.sh {stream}"

